---
- name: Check and wait for maintenance window
  ansible.builtin.import_tasks: check_window.yml

- name: Apply patches
  ansible.builtin.import_tasks: patch.yml

- name: Handle post-patch reboot
  ansible.builtin.import_tasks: reboot.yml
