---
ubuntu_patch_maintenance_window_start: "02:00"
ubuntu_patch_maintenance_window_end: "06:00"

ubuntu_patch_reboot_window_start: "04:00"
ubuntu_patch_reboot_window_end: "06:00"

ubuntu_patch_reboot_if_required: true
ubuntu_patch_upgrade_type: "security"
